### ISSUE TITLE
Can't reinstall after upgrade

### ISSUE THREAD

**Issue by n7qnm** [natekspencer/hacs-vivint#101]
Upgraded package and am now seeing the following errors:
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2023-03-30 11:12:06.103 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package vivintpy==2023.3.3: ERROR: Cannot install vivintpy==2023.3.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2023-03-30 11:12:40.869 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package vivintpy==2023.3.3: ERROR: Cannot install vivintpy==2023.3.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2023-03-30 11:12:40.877 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/lib/python3.10/site-packages/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)

**Comment by natekspencer** [comment]
What version of HA are you running?

**Comment by n7qnm** [comment]
Home Assistant 2022.12.8Frontend 20221213.1 – latest

**Comment by natekspencer** [comment]
You'll either need to downgrade this integration or update Home Assistant. I can't remember what the minimum version this requires is, but it for sure works on HA 2023.3.*
