### ISSUE TITLE
Support for Triggering Alarm from HA

### ISSUE THREAD

**Issue by fxfitz** [natekspencer/hacs-vivint#132]
### The request

I don't THINK this exists, so please correct me if I'm dumb and just missed it, but would it be possible to trigger the Vivint alarm from HA?

The use case being that I have several non-Vivint motion sensors and door sensors that are directly tied to HA, and it would be great if I could use those to trigger the HA alarm.

TIA!

**Comment by Bobbyiv** [comment]
Have you tried the Alarm Control Panel Trigger service (alarm_control_panel.alarm_trigger)?

**Comment by fxfitz** [comment]
... Nope, I sure didn't try it, and it totally works! I was looking for a Vivint-specific service 🤦‍♂️

While the alarm did go off, I did get an error though. I can open another ticket for it, but doesn't seem like there's much to go on from the logs (because the alarm _did_ trigger):

```
2024-04-18 08:52:28.800 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546705362112] Error handling message: Unknown error (unknown_error) Fran from 192.168.3.145 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 794, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1713, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 457, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 509, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 539, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 507, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2543, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2580, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 971, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1043, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/vivint/alarm_control_panel.py", line 110, in async_alarm_trigger
    await self.device.trigger_alarm()
  File "/usr/local/lib/python3.12/site-packages/vivintpy/devices/alarm_panel.py", line 137, in trigger_alarm
    await self.api.trigger_alarm(self.id, self.partition_id)
  File "/usr/local/lib/python3.12/site-packages/vivintpy/vivintskyapi.py", line 180, in trigger_alarm
    raise VivintSkyApiError("Failed to trigger alarm")
vivintpy.exceptions.VivintSkyApiError: Failed to trigger alarm
```

**Comment by fxfitz** [comment]
Got it.

Will do this weekend and post the results!

**Comment by fxfitz** [comment]
Whelp. Totally forgot to do the test. I'll see if I can do it tonight!

**Comment by fxfitz** [comment]
So I set the default logging level to debug:

```
logger:
  default: debug
```

And I'm not seeing anything more in the logs. Is there something specific I should be searching for? Or is there a way to _only_ make the vivint integration log at debug?

**Comment by natekspencer** [comment]
> Or is there a way to _only_ make the vivint integration log at debug?

If you go to an integration, you can enable debug logging specifically for that domain: ![Screenshot 2024-05-20 at 09 29 37](https://github.com/natekspencer/hacs-vivint/assets/3792831/9b1c6d8d-8557-41e3-b457-e411838cc0fb)
