### ISSUE TITLE
Home Assistant 12.10 broke Vivint

### ISSUE THREAD

**Issue by 007GTCS** [natekspencer/hacs-vivint#35]
Upgrading to home assistant 12.10 broke the integrating. See the log below

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/vivint/hub.py:94 
Integration: Vivint (documentation, issues) 
First occurred: 10:39:29 PM (1 occurrences) 
Last logged: 10:39:29 PM

Error setting up entry username@gmail.com for vivint
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/vivint/__init__.py", line 59, in async_setup_entry
    await hub.login(load_devices=True, subscribe_for_realtime_updates=True)
  File "/config/custom_components/vivint/hub.py", line 94, in login
    await self.account.connect(
  File "/usr/local/lib/python3.9/site-packages/vivintpy/account.py", line 72, in connect
    await self.subscribe_for_realtime_updates(authuser_data)
  File "/usr/local/lib/python3.9/site-packages/vivintpy/account.py", line 167, in subscribe_for_realtime_updates
    self.__pubnub = PubNubAsyncio(pnconfig)
  File "/usr/local/lib/python3.9/site-packages/pubnub/pubnub_asyncio.py", line 38, in __init__
    super(PubNubAsyncio, self).__init__(config)
  File "/usr/local/lib/python3.9/site-packages/pubnub/pubnub_core.py", line 78, in __init__
    self.config.validate()
  File "/usr/local/lib/python3.9/site-packages/pubnub/pnconfiguration.py", line 38, in validate
    PNConfiguration.validate_not_empty_string(self.uuid)
  File "/usr/local/lib/python3.9/site-packages/pubnub/pnconfiguration.py", line 41, in validate_not_empty_string
    assert value and isinstance(value, str) and value.strip() != "", "UUID missing or invalid type"
AssertionError: UUID missing or invalid type

**Comment by mat1583** [comment]
Confirming, with the same error. Reverting to previous version at the moment.

**Comment by ruikenshin** [comment]
confirmed as well...does work in 12.9 but is broken in 12.10 release

**Comment by apercrcl01** [comment]
Confirmed.  Reverted back to 12.9

**Comment by natekspencer** [comment]
Pubnub released a breaking change yesterday which caused the issue. The upgrade to HA 12.10 just allowed for it to be updated as well. I've limited the version in vivintpy and updated the requirement in release 2022.1.0, so this should be fixed.

**Comment by mat1583** [comment]
Thanks once again for the quick response and fix!
