### ISSUE TITLE
Issue with HA 2022.2

### ISSUE THREAD

**Issue by garettharnish** [natekspencer/hacs-vivint#37]
My guess is its a compability issue with pubnub, but vivntypy's requirement is 5.5.0 and I have that.

Any thoughts?

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/hass/.homeassistant/custom_components/vivint/__init__.py", line 59, in async_setup_entry
    await hub.login(load_devices=True, subscribe_for_realtime_updates=True)
  File "/home/hass/.homeassistant/custom_components/vivint/hub.py", line 94, in login
    await self.account.connect(
  File "/srv/homeassistant/lib/python3.9/site-packages/vivintpy/account.py", line 72, in connect
    await self.subscribe_for_realtime_updates(authuser_data)
  File "/srv/homeassistant/lib/python3.9/site-packages/vivintpy/account.py", line 167, in subscribe_for_realtime_updates
    self.__pubnub = PubNubAsyncio(pnconfig)
  File "/srv/homeassistant/lib/python3.9/site-packages/pubnub/pubnub_asyncio.py", line 38, in __init__
    super(PubNubAsyncio, self).__init__(config)
  File "/srv/homeassistant/lib/python3.9/site-packages/pubnub/pubnub_core.py", line 78, in __init__
    self.config.validate()
  File "/srv/homeassistant/lib/python3.9/site-packages/pubnub/pnconfiguration.py", line 38, in validate
    def validate(self):
  File "/srv/homeassistant/lib/python3.9/site-packages/pubnub/pnconfiguration.py", line 41, in validate_not_empty_string
    if not self.uuid:
AssertionError: UUID missing or invalid type

**Comment by natekspencer** [comment]
This has already been answered in two separate issues:

https://github.com/natekspencer/hacs-vivint/issues/35
https://github.com/natekspencer/hacs-vivint/issues/36

**Comment by garettharnish** [comment]
Apologies.  I failed to check closed issues.   I had upgraded to the newest version, but I had to completely remove the custom integration, start hass, then put back in the new version for the custom integration and then restart for it to correctly load 2022.01.

**Comment by amathews84** [comment]
> Apologies. I failed to check closed issues. I had upgraded to the newest version, but I had to completely remove the custom integration, start hass, then put back in the new version for the custom integration and then restart for it to correctly load 2022.01.

Is this the only way to fix it or will installing the next update in HACS (whenever that may be) take care of it?

**Comment by garettharnish** [comment]
I had to remove and readd.  I had upgraded and restarted thinking that would fix it.

**Comment by amathews84** [comment]
> 

Noob question here but if you do it that way do you have to redo all associated lovelace entities/cards?

**Comment by garettharnish** [comment]
To be more specific, I move the directory our of the custom_components directory and started up HASS (which listed the integration as broken).  I then moved it back and restarted HASS and it all came back.  All lovelace entities/cards remained.   I'm not 100% certain what uninstall it with HACS directly would do.
