### ISSUE TITLE
Battery Sensors Unavailable

### ISSUE THREAD

**Issue by ebotty** [natekspencer/hacs-vivint#46]
I'm not sure when this happened, as I only recently noticed, but all battery sensor entities for my Vivint devices are currently unavailable.
![image](https://user-images.githubusercontent.com/69599786/164019514-ace82416-5754-4fe3-8f23-9cce99db29cc.png)

```
Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:529
Integration: Sensor (documentation, issues)
First occurred: 9:11:45 AM (4 occurrences)
Last logged: 9:23:37 AM

Error adding entities for domain sensor with platform vivint
Error while setting up vivint platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

Let me know if I can give more info.

**Comment by natekspencer** [comment]
This is resolved in the latest release of this integration: 2022.4.0.
