### ISSUE TITLE
Broken in HA 2023.3.0

### ISSUE THREAD

**Issue by droolingtaz** [natekspencer/hacs-vivint#79]
After upgrading to 2023.3 the vivint integration shows unable to setup.  Details are below:

Logger: homeassistant.config_entries
Source: custom_components/vivint/hub.py:94
Integration: Vivint ([documentation](https://github.com/natekspencer/hacs-vivint), [issues](https://github.com/natekspencer/hacs-vivint/issues))
First occurred: 1:18:27 PM (2 occurrences)
Last logged: 2:06:35 PM

Error setting up entry Alarm System for vivint
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/vivint/__init__.py", line 53, in async_setup_entry
    await hub.login(load_devices=True, subscribe_for_realtime_updates=True)
  File "/config/custom_components/vivint/hub.py", line 94, in login
    await self.account.connect(
  File "/usr/local/lib/python3.10/site-packages/vivintpy/account.py", line 65, in connect
    authuser_data = await self.vivintskyapi.connect()
  File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 69, in connect
    authuser_data = await self.get_authuser_data()
  File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 99, in get_authuser_data
    resp = await self.__get("authuser")
  File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 376, in __get
    return await self.__call(
  File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 417, in __call
    resp = await method(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 493, in _request
    all_cookies = self._cookie_jar.filter_cookies(url)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 239, in filter_cookies
    self._do_expiration()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 150, in _do_expiration
    self.clear(lambda x: False)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 115, in clear
    for (domain, path), cookie in self._cookies.items():
ValueError: too many values to unpack (expected 2)

**Comment by natekspencer** [comment]
This should be resolved in release 2023.2.2

**Comment by droolingtaz** [comment]
Upgraded to 2023.2.2 and appears to have the same error.

**Comment by natekspencer** [comment]
@droolingtaz / @Bobbyiv, can you check to see if there is ".vivintpy_cache.pickle" file in your config directory and delete it? Or an uninstall of the integration and then reinstall will also clear that file. It looks like the error now is stemming from loading a cached file with cookies since aiohttp 3.8.4 stores them as tuples instead of a string: https://github.com/aio-libs/aiohttp/issues/7216

**Comment by droolingtaz** [comment]
BOOM!!!  @natekspencer confirmed that resolved the issue.  Thank you!!!

**Comment by Bobbyiv** [comment]
Thank you.
I deleted the the ".vivintpy_cache.pickle" from the config file, rebooted Home Assistant, and Vivint loaded.

**Comment by natekspencer** [comment]
This should automatically be resolved in release 2023.2.3, but will also require a reauth
